name: fasa
description: Support for parsing a somewhat natural language expression into objects for use in Finance applications.
version: 0.1.0
repository: https://github.com/zikani03/fasa

environment:
  sdk: ^3.4.4

dependencies:
  formula_parser: ^2.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
